name: build_test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: test
      run: |
        sudo -E apt update
        sudo -E apt install neofetch -y
        neofetch
        uname -a
        df -h
        cat /etc/os-release 
