name: build_test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: test
      run: |
        uname -a
        df -h
        cat /etc/os-release 
        id
        pwd
        
    - name: test2
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo -E apt-get update
        echo update
        sudo -E apt-get install libev-dev libpam0g-dev libtirpc-dev liblzma5 libsnmp-dev
        echo install

