name: build_test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: test
      run: |
        apt-get update
        uname -a
        df -h
        cat /etc/os-release 
