name: build_test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: test
      run: |
        uname -a
        df -h
        cat /etc/os-release 
        id
        pwd
        
    - name: test2
      run: |
        python3 --version

